
// @optional ./animate.js
// @optional ./animate_prop.js
// @optional ./diff.js
// @optional ./elements.js
// @optional ./event_namespacer.js
// @optional ./event_xy.js
// @optional ./get_rect.js
// @optional ./has_attribute.js
// @optional ./hsl.js
// @optional ./is_attached.js
// @optional ./is_editable.js
// @optional ./is_event.js
// @optional ./is_focused.js
// @optional ./is_visible.js
// @optional ./is_widget.js
// @optional ./make_event.js
// @optional ./remove.js
// @optional ./scroll.js
