
/* =========================================================================
 * Svelto - Tasks - Config - Defaults (Components)
 * =========================================================================
 * Copyright (c) 2015-2016 Fabio Spampinato
 * Licensed under MIT (https://github.com/svelto/svelto/blob/master/LICENSE)
 * ========================================================================= */

/* COMPONENTS */

var components = [
  'accordion',
  'animations',
  'autogrow',
  // 'autogrow/input',
  // 'autogrow/textarea',
  'base',
  'blur',
  // 'boilerplate',
  'breadcrumb',
  'breakpoints',
  'browser',
  'bteach',
  'button',
  'card',
  'carousel',
  'chat',
  'checkbox',
  'closer',
  'color',
  'colorpicker',
  'colors',
  'constants',
  'container',
  'cookie',
  'core',
  'datepicker',
  'divider',
  'draggable',
  'dropdown',
  'droppable',
  'embedded',
  'embedded_css',
  'expander',
  'extras',
  'factory',
  'flags',
  'flickable',
  'flippable',
  'footer',
  'form',
  'form_ajax',
  'form_sync',
  'form_validate',
  'grid',
  'header',
  'helpers',
  'helpers_responsive',
  'highlight',
  'icons',
  'image',
  'infobar',
  'input',
  'keyboard',
  'keyframes',
  'label',
  // 'mixins', //FIXME: Does it behave as a component or is it a special folder?
  'modal',
  'mouse',
  'multiple',
  'n_times_action',
  'normalize',
  'notification',
  'noty',
  'one_time_action',
  'opener',
  'outline',
  'overlay',
  'pager',
  'panel',
  'parallax',
  'placeholder',
  'pointer',
  'positionate',
  'prism',
  'progressbar',
  'radio',
  'raisable',
  'rater',
  'regexes',
  'remote',
  // 'remote/action',
  // 'remote/modal',
  'ripple',
  'route',
  'sections',
  'select',
  'selectable',
  'shapes',
  'sizes',
  'slider',
  'sortable',
  'spinner',
  'spinner_overlay',
  'statistic',
  'stepper',
  'svelto',
  'switch',
  'table',
  'table_helper',
  'tabs',
  'tagbox',
  'targeter',
  'textarea',
  'time_ago',
  'timer',
  'tmpl',
  'toggler',
  'toolbar',
  'tooltip',
  'touching',
  'transform',
  'typography',
  'validator',
  // 'variables', //FIXME: Does it behave as a component or is it a special folder?
  'widget',
  'widgetize',
  'z_depths'
];

/* EXPORT */

module.exports = components;
